### ISSUE TITLE
Settings interface: "Maintain Standard Login" is always shown checked/enabled

### ISSUE THREAD

**Issue by gjdev** [brandonaaron/redmine_rubycas#7]
The Maintain Standard Login setting in the settings page always shows as checked/enabled, even after disabling and saving.

(The state seems to be saved correctly, just not shown correctly on the management interface).

**Comment by brandonaaron** [comment]
Fixed in c38b83d95881c67eb828760ae2c62f6e717f9d3d

**Comment by gjdev** [comment]
I pulled in your changes and restarted redmine, but I see no change in behavior. "Maintain Standard Login" is still shown checked regardless of state.

**Comment by gjdev** [comment]
Sorry it is working correctly now. Don't know why it didn't seem so right after the update, but anyway, thanks a bunch for the super quick fix!
